// Edit the provider list, then run npm run banner:generate.
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';

const providers = [
  { name: 'Cursor', icon: 'cursor' },
  { name: 'Antigravity', icon: 'antigravity' },
  { name: 'OpenCode Zen', icon: 'opencode' },
  { name: 'OpenAI Codex', icon: 'openai' },
];

// Small, editable vector marks; no raster images or remote logo dependencies.
const icons = {
  antigravity:
    '<path d="M-43 34C-26 22-25-39 0-40 25-39 26 22 43 34 48 42 30 37 25 30 15 13 10-2 0-2S-15 13-25 30C-30 37-48 42-43 34Z" fill="currentColor"/>',
  opencode:
    '<path fill="currentColor" fill-rule="evenodd" d="M-29-38H29V38H-29ZM-17-26V26H17V-26Z"/><path fill="currentColor" d="M-10-10H10V24H-10Z"/>',
  cursor:
    '<path d="M0-40 35-20V20L0 40-35 20V-20Z" fill="none" stroke="currentColor" stroke-width="4"/><path d="M-35-20H35L17 16 0 40V0Z" fill="currentColor"/>',
  // OpenAI mark: Simple Icons 11.0.0, CC0; source links in docs/assets/README.md.
  openai:
    '<path transform="translate(-40 -40) scale(3.3333)" fill="currentColor" d="M22.2819 9.8211a5.9847 5.9847 0 0 0-.5157-4.9108 6.0462 6.0462 0 0 0-6.5098-2.9A6.0651 6.0651 0 0 0 4.9807 4.1818a5.9847 5.9847 0 0 0-3.9977 2.9 6.0462 6.0462 0 0 0 .7427 7.0966 5.98 5.98 0 0 0 .511 4.9107 6.051 6.051 0 0 0 6.5146 2.9001A5.9847 5.9847 0 0 0 13.2599 24a6.0557 6.0557 0 0 0 5.7718-4.2058 5.9894 5.9894 0 0 0 3.9977-2.9001 6.0557 6.0557 0 0 0-.7475-7.0729zm-9.022 12.6081a4.4755 4.4755 0 0 1-2.8764-1.0408l.1419-.0804 4.7783-2.7582a.7948.7948 0 0 0 .3927-.6813v-6.7369l2.02 1.1686a.071.071 0 0 1 .038.052v5.5826a4.504 4.504 0 0 1-4.4945 4.4944zm-9.6607-4.1254a4.4708 4.4708 0 0 1-.5346-3.0137l.142.0852 4.783 2.7582a.7712.7712 0 0 0 .7806 0l5.8428-3.3685v2.3324a.0804.0804 0 0 1-.0332.0615L9.74 19.9502a4.4992 4.4992 0 0 1-6.1408-1.6464zM2.3408 7.8956a4.485 4.485 0 0 1 2.3655-1.9728V11.6a.7664.7664 0 0 0 .3879.6765l5.8144 3.3543-2.0201 1.1685a.0757.0757 0 0 1-.071 0l-4.8303-2.7865A4.504 4.504 0 0 1 2.3408 7.872zm16.5963 3.8558L13.1038 8.364 15.1192 7.2a.0757.0757 0 0 1 .071 0l4.8303 2.7913a4.4944 4.4944 0 0 1-.6765 8.1042v-5.6772a.79.79 0 0 0-.407-.667zm2.0107-3.0231l-.142-.0852-4.7735-2.7818a.7759.7759 0 0 0-.7854 0L9.409 9.2297V6.8974a.0662.0662 0 0 1 .0284-.0615l4.8303-2.7866a4.4992 4.4992 0 0 1 6.6802 4.66zM8.3065 12.863l-2.02-1.1638a.0804.0804 0 0 1-.038-.0567V6.0742a4.4992 4.4992 0 0 1 7.3757-3.4537l-.142.0805L8.704 5.459a.7948.7948 0 0 0-.3927.6813zm1.0976-2.3654l2.602-1.4998 2.6069 1.4998v2.9994l-2.5974 1.4997-2.6067-1.4997Z"/>',
};
const xml = (value) => String(value).replace(/[<>&"']/g, (c) => `&#${c.charCodeAt(0)};`);
assert(providers.length > 0);
assert.equal(new Set(providers.map((provider) => provider.name)).size, providers.length);
for (const provider of providers) {
  assert(Object.hasOwn(icons, provider.icon), `Missing SVG icon for ${provider.name}`);
  assert(provider.name.length <= 18, 'Keep labels short enough for the provider layout');
}

const rows = Math.ceil(providers.length / 2);
const height = Math.max(548, rows * 166 + 50);
const centerX = 910;
const centerY = height / 2;
const nodes = providers
  .map((provider, index) => {
    const x = index % 2 === 0 ? 728 : 1096;
    const row = providers.length === 2 ? index : Math.floor(index / 2);
    const y =
      providers.length === 1 ? centerY - 20 : 108 + row * ((height - 224) / Math.max(1, rows - 1));
    // Keep endpoint dots clear of wide marks and their labels (especially Antigravity).
    const dx = x - centerX;
    const dy = y - centerY;
    const distance = Math.hypot(dx, dy);
    const startX = centerX + (dx / distance) * 85;
    const startY = centerY + (dy / distance) * 85;
    const endX = x - (dx / distance) * 100;
    const endY = y - (dy / distance) * 100;
    return `
  <g class="provider" aria-label="${xml(provider.name)}">
    <path d="M${startX.toFixed(1)} ${startY.toFixed(1)} ${endX.toFixed(1)} ${endY.toFixed(1)}" fill="none" stroke="currentColor" stroke-width="4"/>
    <circle cx="${endX.toFixed(1)}" cy="${endY.toFixed(1)}" r="7" fill="currentColor"/>
    <g transform="translate(${x} ${y})">${icons[provider.icon]}</g>
    <text x="${x}" y="${y + 72}" text-anchor="middle" font-size="22">${xml(provider.name)}</text>
  </g>`;
  })
  .join('');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="${height}" viewBox="0 0 1280 ${height}" role="img" aria-labelledby="title description">
  <!-- Generated by scripts/banner.mjs. Edit its provider list, then npm run banner:generate. -->
  <title id="title">multi-cli — plugin for claude code</title>
  <desc id="description">A pixel mascot connects Claude Code to external models and coding harnesses. ${xml(providers.map((p) => p.name).join(', '))}.</desc>
  <defs>
    <style>
      text { font-family: 'DejaVu Sans', sans-serif; fill: currentColor; }
      .mono { font-family: 'DejaVu Sans Mono', monospace; }
      .provider { color: #d97757; }
    </style>
  </defs>
  <rect width="1280" height="${height}" fill="#000000"/>
  <g transform="translate(94 ${centerY - 10})" color="#faf9f5">
    <text class="mono" font-size="56" font-weight="700" letter-spacing="-1">multi-cli<tspan fill="#d97757">_</tspan></text>
    <text class="mono" y="62" font-size="29">plugin for claude code</text>
  </g>
  ${nodes}
  <g transform="translate(${centerX - 70} ${centerY - 45})" fill="#d97757">
    <path fill-rule="evenodd" d="M22 0H118V24H140V48H118V90H106V70H94V90H82V70H58V90H46V70H34V90H22V48H0V24H22ZM34 12V24H46V12ZM94 12V24H106V12Z"/>
  </g>
</svg>
`;

const destination = new URL('../docs/assets/banner.svg', import.meta.url);
if (process.argv.includes('--check')) {
  assert.equal(await readFile(destination, 'utf8'), svg, 'Run npm run banner:generate');
  console.log('Banner is up to date.');
} else {
  await writeFile(destination, svg);
  console.log('Wrote docs/assets/banner.svg');
}
